package edu.cmu.cs.cs214.hw5.framework.core;

import java.util.Date;
import java.util.List;
import java.util.Optional;

/**
 * The {@code AnalyzedPost} class represents an analyzed post with a post and a sentiment.
 * AnalyzedPosts are generated by the framework from SimplePosts using GoogleNLP API.
 *
 * @author Team6
 */
public final class AnalyzedPost implements Post {
    private Sentiment sentiment;
    private Post post;

    /**
     * Initializes a new {@code AnalyzedPost} from a post and a sentiment.
     *
     * @param post          {@code Post} that is the source of post content
     * @param sentiment     {@code Sentiment} that is associated with the post
     */
    public AnalyzedPost(Post post, Sentiment sentiment) {
        this.post = post;
        this.sentiment = sentiment;
    }

    @Override
    public Date getTimeStamp() {
        return post.getTimeStamp();
    }

    @Override
    public Optional<String> getLocation() {
        return post.getLocation();
    }

    @Override
    public String getContent() {
        return post.getContent();
    }

    public Sentiment getSentiment() {
        return sentiment;
    }

    @Override
    public String toString() {
        return String.format("AnalyzedPost{%s, %s}", post.toString(), sentiment.toString());
    }
}
